default:
  - nombre: "MasxMenos"
    url_base: "https://www.masxmenos.cr/"
    xpath_precio: "//div[contains(@class, 'vtex-store-components-3-x-priceContainer')]//span[contains(@class, 'vtex-store-components-3-x-sellingPriceValue')]"
    productos:
      - nombre: "Leche"
        url_producto: "leche-dos-pinos-semidescremada-1000ml-2/p"
        categoria: "Lácteos"
      - nombre: "Arroz"
        url_producto: "arroz-tio-pelon-entero-99-4000gr/p"
        categoria: "Abarrotes"