default:
  - nombre: "MasxMenos"
    url_base: "https://www.masxmenos.cr/"
    xpath_precio: "//div[contains(@class, 'vtex-store-components-3-x-priceContainer')]//span[contains(@class, 'vtex-store-components-3-x-sellingPriceValue')]"
    productos:
      - nombre: "Leche"
        url_producto: "leche-dos-pinos-semidescremada-1000ml-2/p"
        categoria: "Lácteos"
      - nombre: "Arroz"
        url_producto: "arroz-tio-pelon-entero-99-4000gr/p"
        categoria: "Abarrotes"
  - nombre: "Automercado"
    url_base: "https://www.automercado.cr/"
    xpath_precio: "//div[contains(@class, 'h5-am')]"
    productos:
      - nombre: "Leche"
        url_producto: "p/leche-semi-descremada-dos-pinos-caja-1000-ml/id/8abe4018-b1fb-4fed-86e6-5710de9a4a20"
        categoria: "Lácteos"
      - nombre: "Arroz"
        url_producto: "p/arroz-blanco-99%2525-tio-pelon-paquete-4000-g/id/120dd829-dff5-428c-b85a-0d5259594ab9"
        categoria: "Abarrotes"
  - nombre: "Maxipali"
    url_base: "https://www.maxipali.co.cr/"
    xpath_precio: "//div[contains(@class, 'vtex-store-components-3-x-priceContainer')]//span[contains(@class, 'vtex-store-components-3-x-sellingPriceValue')]/span"
    productos:
      - nombre: "Leche"
        url_producto: "leche-coronado-liquido-descremada-0-grasa-tb-1000ml-2/p"
        categoria: "Lácteos"
      - nombre: "Arroz"
        url_producto: "arroz-indiana-entero-99-4000gr/p"
        categoria: "Abarrotes"