name: Scrape and Commit Data

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  schedule:
    - cron: '0 */6 * * *'
jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permisos necesarios para que el GITHUB_TOKEN pueda hacer commit y push

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'  # Asegúrate de usar la versión de R que necesitas
     
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      
    - name: Restore R environment using renv
      uses: r-lib/actions/setup-renv@v2

    - name: Run scraping script
      run: Rscript setup.R

    - name: Auto-commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update database with new scraped data"
        branch: main  # Asegúrate de ajustar esto a la rama que estás usando
        file_pattern: data/precios.duckdb
